### ISSUE TITLE
Feature Request: /health

### ISSUE THREAD

**Issue by mcastorina** [kilogram/autogm#8]
Typing `/health` will display your current health over max health (i.e. `10/19`)
If possible, only displays to the person who made the request.

**Comment by kilogram** [comment]
This is dependent on full character stat management in the app.

**Comment by mcastorina** [comment]
This does not depend on full character stat management, it is simply reading from the spreadsheet and reporting it in slack.

**Comment by kilogram** [comment]
Let's make it a generic query then, so that other fields (inc. custom fields) can also be queried.

**Comment by kilogram** [comment]
Won't Fix (Obsolete)
